[project]
name = "ragwise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "docling-ibm-models>=3.14.0",
    "docling-parse>=7.15.0",
    "docling-slim[convert-core,docling-parse,extract-core,feat-chunking,format-html,format-html-render,format-pdf-pypdfium2]",
    "feedparser>=6.0.14",
    "flagembedding>=1.4.2",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "requests>=2.34.2",
]

[tool.uv.sources]
docling-slim = { git = "https://github.com/medjmalami/docling.git", rev = "2b63ba80dafeed09d36efeccba347f7753f57810" }
